### ISSUE TITLE
Source code is displaying in the Experiment Simulations

### ISSUE THREAD

**Issue by madhavipuliraju** [openedx-vlead/open-edx-electrical-machines-lab-iitr#1]
Source code is displaying in the following experiment:
1) Speed control of DC motor by using Ward- Leonard Method of speed control
2) Load Characteristics of DC shunt generator 
3) Magnetisation Characteristics of DC shunt generator 
4) Determination of the efficiency of a dc motor by loss summation method(Swinburne's test) 
5) Speed control of slipring Induction Motor 
6)  Determination of Transformer equivalent circuit from Open Circuit and Short Circuit Test

**Comment by sivashankerN** [comment]
This issue is fixed as this lab has no such problems as of now
